Add run_person_match
cleanchoice/ds-jed pull request #7
Opened 2023-01-13 18:46 UTC by a9mike

Add run_person_match

Add function run_person_match which will add voterbase_id. Add some supporting function in executor.py

2023-01-13 22:24 UTC, follperson requested changes
double check that `if create_voterbase_id` piece - is that meant to be a `sql_update += ...`?

2023-01-13 22:24 UTC, follperson commented on jed/processor/configs.py
> +MONTHLY_VOTERFILE = 219
:+1:

2023-01-13 22:24 UTC, follperson commented on jed/processor/matcher.py
> +    civis.futures.CivisFuture(civis_client.jobs.get_runs, args)
maybe add some logging?

2023-01-13 22:24 UTC, follperson commented on jed/processor/matcher.py
> +        """
maybe make this an if else? otherwise it seems like it could be unintentional behavior where you overwrite the previous query

2023-01-13 22:57 UTC, a9mike commented on jed/processor/matcher.py
> +        """
I've found this to be a cleaner way to write if/else statements, as it shows there is a default and then has to indent less text. It's my preferred method. Fun fact, I put this code through ChatGPT and it also suggested getting rid of `else`. :)

2023-01-13 23:00 UTC, a9mike commented on jed/processor/matcher.py
> +    civis.futures.CivisFuture(civis_client.jobs.get_runs, args)
I think I might leave that to whatever function utilizes it, so it goes to the appropriate file. When refactoring the basefile_refresh it felt more confusing and disorganized to have logs within specific functions, on top of having them in the program being run, if that makes sense. But open to it if you have ideas on how to streamline. 🤷‍♀️

2023-01-13 23:01 UTC, a9mike commented
> 

The original code is NOT sql update. I don't want to mess with this code too much now because I'm not sure what unintended effects it will have, but that is definitely a good thought. I haven't parsed out why adding `voterbase_id` is optional either, seems like if that doesn't get added there's a lot of processing but no tangible output or reason for running the code. Any ideas there? :/

2023-01-18 13:40 UTC, follperson commented on jed/processor/matcher.py
> +        """
okay, just wanted to be sure it was the desired behavior

2023-01-18 13:47 UTC, follperson commented on jed/processor/matcher.py
> +    civis.futures.CivisFuture(civis_client.jobs.get_runs, args)
Yeah i get what you are saying. Usually I like them in the function that is getting run - then you only have to write them once, vs writing them everytime you use the function in your higher level program(s). At least as 'debug' level statements where we can turn them off or on depending on the level of error. My preference really is to use a stream logger with info level, and a file logger with debug level. 
 Generally, I think that if you are obscuring some debugging supports (eg the response from civis, which sometimes contains an 'error'), you ought to have a way to expose that to the user.

2023-01-18 13:49 UTC, follperson commented on jed/processor/matcher.py
> +    civis.futures.CivisFuture(civis_client.jobs.get_runs, args)
But i think it's pretty cumbersome to implement logging tbh so it can wait a little bit

2023-01-18 13:53 UTC, follperson commented
No idea about the voterbase_id...

2023-01-18 13:54 UTC, follperson approved these changes

2023-01-18 17:48 UTC, merged